version: '3'

services:
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile-nginx
        volumes:
            - ./symfony/:/var/www/html/
        ports:
            - 80:80
        networks:
            - symfony
        volumes_from: 
            - practice
    practice:
        container_name: practice
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile-php
        environment:
            APP_ENV: dev
            DATABASE_URL: "mysql://uomauihk1orxupv6:X0At4I9NZsMkaVFDDkem@btjn4ndufeonouldpgvz-mysql.services.clever-cloud.com:3306/btjn4ndufeonouldpgvz"
        expose:
            - 9000
        volumes:
            - ./symfony/:/var/www/html/
        networks:
            - symfony           
networks:
    symfony:
volumes:
    symfony:
