version: '3'

services:
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile-nginx
        volumes:
            - ./symfony/:/var/www/html/
        ports:
            - 8011:80
        networks:
            - symfony
        depends_on: 
            - php
    php:
        container_name: php
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile-php
        environment:
            APP_ENV: dev
            DATABASE_URL: "mysql://newuser:password@mysql:3306/userManagementSys"
        expose:
            - 9000
        volumes:
            - ./symfony/:/var/www/html/
        networks:
            - symfony
        depends_on: 
            - mysql
    mysql:
        container_name: mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ~/db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: userManagementSys
            MYSQL_USER: newuser
            MYSQL_PASSWORD: password
        networks:
            - symfony
        ports:
            - 3306:3306            
networks:
    symfony:
volumes:
    db_data:
    symfony:
